### ISSUE TITLE
remote_execution.pb.go does not take over comment from remote_execution.proto

### ISSUE THREAD

**Issue by atetubou** [bazelbuild/remote-apis#107]
If [remote_execution.pb.go](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.pb.go) takes over comment from [remote_execution.proto](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto), [godoc](https://godoc.org/github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2) becomes more useful.

**Comment by mostynb** [comment]
I think this is a limitation of protoc-gen-go:
https://github.com/golang/protobuf/issues/666
