### ISSUE TITLE
[remote asset api] resource_type qualifier is too vague

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/remote-apis#118]
The remote asset api refers to `resource_type` as a recommended qualifier to resolve ambiguities, but the Qualifier Lexicon file merely has this circular definition: `resource_type: This describes the type of resource`. It's the only standard qualifier in the doc without examples- I think we should add some.

**Comment by bergsieker** [comment]
@sstriker WDYT about this?

**Comment by sstriker** [comment]
That warrants an example.  I intended to just use well-known media types.

I remember looking for an example for a git repository... But there are no
media types for directories.

I'll put together a PR to resolve.
