### ISSUE TITLE
CI hooks: generate go bindings

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/remote-apis#162]
It would be good to add a CI hook, which either checks the generated go bindings are up to date, or generates them itself and updates the PR somehow.

**Comment by sstriker** [comment]
+1, great idea.  Would this be achievable with GitHub Actions?

**Comment by mostynb** [comment]
I believe so. Here's an example action which commits and then pushes to origin: https://lannonbr.com/blog/2019-12-09-git-commit-in-actions

Our action could run `hooks/pre-commit` when master is updated, and if there are any changes commit and push to master. I can investigate this next week, if you like.

**Comment by mostynb** [comment]
Closing this, in favour of #177.
