### ISSUE TITLE
feature request: stream stdout/stderr while the command is still being executed remotely

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/remote-apis#211]
There was a thread on bazel slack where someone wanted a feature where the stdout/stderr of long-running commands could be streamed back to the client. The use case was a long-running command (10s of minutes), which would sometimes print warnings very early in the execution that the user could act upon without waiting for the command to finish.

I asked if a wrapper script could be used, which parses the logs which indicate that the command would eventually fail and exit at that point, but the desire was for the users to make a judgement call on which logs to act on.

**Comment by EdSchouten** [comment]
REv2 already supports that, right?

https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/execution/v2/remote_execution.proto#L1413

**Comment by mostynb** [comment]
Thanks- forwarded this info on.

I had missed this due to the string typing. So the resource name can be any format selected by the server that isn't confused with CAS blobs, and for now clients must assume that the returned data is uncompressed?

**Comment by EdSchouten** [comment]
Yep!
