### ISSUE TITLE
Non-Bazel Server Example

### ISSUE THREAD

**Issue by asml-mdroogle** [bazelbuild/remote-apis#228]
This API is designed to be agnostic to Bazel, but are there any working (even toy) example servers of this working without Bazel. The list of servers appear to all use Bazel.

Something simple like running gcc would be a good example.

**Comment by EdSchouten** [comment]
> The list of servers appear to all use Bazel.

Even though at least Buildbarn & Buildfarm project use Bazel as their build system, the resulting software (i.e., the build cluster services) can in principle be used with any client that supports REv2. The README in this repository has a list of clients, which should in theory all work against the servers listed:

https://github.com/bazelbuild/remote-apis#clients

**Comment by asml-mdroogle** [comment]
indeed, I see now I misunderstood how tightly coupled the buildservers are with Bazel
