### ISSUE TITLE
Move Remote Workers API into this repository

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/remote-apis#32]
Per discussions in the monthly meetup, we're going to publish the remote workers API in this repository. Moving the API here will make it easier to handle subsequent changes and clarifications via public issues and PRs rather than the current opaque, Google docs-based process.

For now, we'll move the API itself and provide a link to the existing docs. We expect the existing design doc to transition more gradually (converting it, including the comment threads, to markdown will probably be a decent amount of work) and we don't want to block downstream changes on that step.

**Comment by edbaunton** [comment]
Currently they live here https://github.com/googleapis/googleapis/blob/master/google/devtools/remoteworkers/v1test2/bots.proto

**Comment by buchgr** [comment]
update: @bwkimmel is currently working on moving the api to this repository!

**Comment by bergsieker** [comment]
Per discussions with the remote execution community, there is no longer interest in moving the existing Google RW API into this repo. There is still some interest in adding a simpler RW API to this repo, likely based on the BuildFarm worker API, but that should be tracked in a separate issue (if it's still applicable).
