### ISSUE TITLE
Clarify RW API semantics around bots advertising leases

### ISSUE THREAD

**Issue by bergsieker** [bazelbuild/remote-apis#33]
"Number of Leases" should be defined as an explicit resource, and bots should include the number of supported leases in the Resources that they advertise to the server. This should be clearly documented in the RW API

**Comment by edbaunton** [comment]
I think we agreed that this would only ever be a "suggestion" from the worker - the leases assigned to a worker will always ultimately be the decision of the implementation of the bots interface - right?

i.e. If a worker claims to only support 5 leases and is given 6, it will make a best effort to carry out all 6 and not e.g. fail.

**Comment by bergsieker** [comment]
If we're not moving Google's RW API into this repo as a standard, then I'm not sure this issue is still relevant.
