### ISSUE TITLE
Platforms Standardisation

### ISSUE THREAD

**Issue by edbaunton** [bazelbuild/remote-apis#38]
From the previous Buildfarm meeting there was some discussion around providing standardisation for the Platforms specification in the Remote APIs. This issue is to track the follow-up and see where we should go. 

The benefit we gain by standardising these platform specifications is interopability between services. For example, all services could implement the `DockerImage` specification in the same way and one could seamlessly switch between, e.g. RBE and BuildGrid without have to respecify the platform configuration.

## Current Status
* [Relevant REAPI Proto Section](https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L520)
  * [Google Design Doc](https://docs.google.com/document/d/1AaGk7fOPByEvpAbqeXIyE8HX_A3_axxNnvroblTZ_6s/edit#heading=h.2nk70lyt7xrx)
* [Relevant RWAPI Proto Section](https://github.com/googleapis/googleapis/blob/master/google/devtools/remoteworkers/v1test2/worker.proto#L110)
  * [Google Design Doc](https://docs.google.com/document/d/1s_AzRRD2mdyktKUj2HWBn99rMg_3tcPvdjx3MPbFidU/edit#heading=h.jemd6xa618pu)

Per my understanding, currently there is a mismatch in the way that platforms are specified between the Remote Execution API and the Remote Worker API. The REAPI simply provides a key/value alphabetical list of properties that must be satisfied by the servicing worker owning bot. On the other side, the BotsInterface provides 3 separate attributes for describing in a richer way the executing worker: properties, configurations and devices.

The RWAPI properties are matched against the platform specification exactly to find an appropriate worker. The rest are all 'hints'.

The RWAPI also provides the following conventions:
* Case sensitivity and camelcase
* Standardised keys begin with an uppercase letter
* Standardised keys have standardised values (these will be listed in the proto)

## Standardisation
So far we have come up with the following use cases and keys for standardisation; under this ticket hopefully that can be formalised into the proto. The list is specified [here](https://docs.google.com/document/d/1s_AzRRD2mdyktKUj2HWBn99rMg_3tcPvdjx3MPbFidU/edit#heading=h.tzuzidkiv4lf).

Please update this issue if clarifications/changes are suggested to those keys specified [here](https://docs.google.com/document/d/1s_AzRRD2mdyktKUj2HWBn99rMg_3tcPvdjx3MPbFidU/edit#heading=h.tzuzidkiv4lf).

**Comment by edbaunton** [comment]
My first addition would be of `BaseRootDigest`.

This would specify the ID of a root that would be at "/" (by default) from the point of view of inside the worker (perhaps this could be configurable?). This provides the ability to predefine filesystem that should available during execution so that you don't have to redundantly upload, for example, all the system headers and toolchain if they are well known and predefined.

**Comment by bergsieker** [comment]
@bwkimmel

**Comment by edbaunton** [comment]
@juergbi is tackling this initially in https://github.com/bazelbuild/remote-apis/pull/59
