### ISSUE TITLE
Ambiguity extracting instance names from resource names

### ISSUE THREAD

**Issue by jmacarthur** [bazelbuild/remote-apis#41]
`remote_execution.proto` describes instance names but there appears to be a small hole in the specification:

```
the `instance_name` is an identifier, possibly containing multiple path segments,
```

There are no further restrictions, so the following would appear to be a valid instance name: `uploads/6c92172c-8064-4351-93a2-640d5e8761fe/blobs/187d384348c73a2c0246a42fd061167039e551c1fe8c24a51d9538f4536fa72c/1034`

In which case, if I sent this resource name:

`/uploads/6c92172c-8064-4351-93a2-640d5e8761fe/blobs/187d384348c73a2c0246a42fd061167039e551c1fe8c24a51d9538f4536fa72c/1034/uploads/6c92172c-8064-4351-93a2-640d5e8761fe/blobs/187d384348c73a2c0246a42fd061167039e551c1fe8c24a51d9538f4536fa72c/1034/uploads/6c92172c-8064-4351-93a2-640d5e8761fe/blobs/187d384348c73a2c0246a42fd061167039e551c1fe8c24a51d9538f4536fa72c/1034`

What is the actual instance name and what is the hash of the object requested? I think the instance name could be either one or two repetitions of the first string I posted.

Because anything after the 'size' field is ignored, you cannot pattern match from the right.

I ask because we have an implementation of a remote execution server, and it attempts to determine an optional instance name from the resource name. I'm wondering how to get this code exactly correct.

**Comment by bergsieker** [comment]
I agree with Sander, and actually think we should extend that further:
blobs, actions, and actionResults should all be reserved keywords. I don't
think that places undue restrictions on implementors, and it's a nice,
clear line to draw in the documentation.

**Comment by jmacarthur** [comment]
This sounds good. I think explicitly outlawing 'uploads' is enough, but it shouldn't hurt to add the other words too.

**Comment by bergsieker** [comment]
@ola-rozenfeld WDYT about the reserved keywords suggestion?
