### ISSUE TITLE
ActionResult inline restoration

### ISSUE THREAD

**Issue by werkt** [bazelbuild/remote-apis#46]
I'd like to suggest resurrecting the inline content field in file output relevant fields under ActionResult.

The cached result path is as a gatekeeper to all other action interactions, and serves to throttle extremely heavyweight activity - findMissingBlobs for a huge tree, possibly many [concurrent] writes, executes, and downloads. Minimizing additional requests in the optimized case of getActionResult is therefore of substantial benefits, where cached-result retrieval can outweigh the frequency of missing-forked procedures by extraordinary (i.e. as-many-cached-actions-times-builds you have) factors of load.

With an extension to the GetActionResultRequest to indicate inlining preferences (size limitations, selection mechanisms), we can accommodate ongoing efforts like https://github.com/buchgr/bazel/tree/minimize-downloads as well, and extending ActionResult to be capable of minimized tree delivery could substantially improve that content path as well.

WDYT?

**Comment by bergsieker** [comment]
I'm not sure that we'd have to use the same format for Execute and GetActionResult calls. Cache hits are on the critical path, and it's vital that they be fast. Actual executions are already much, much slower, such that an extra round trip probably doesn't hurt that much.

I'm not saying that we *shouldn't* use the same format for both--there's also value in consistency across the API--but we shouldn't assume that we *have* to do so up front.

One important question to answer is how this information gets specified to Bazel. Is it configurable on the command line, or does Bazel set it automatically based on, for example, spawn strategy? Are we going to need to add another 5 or 6 flags to Bazel?

**Comment by finnball** [comment]
I'd like to be clear on what is being proposed here. Are you suggesting that you would like your output files to be returned inline inside the ActionResult if possible? Is this something that could only be used by the client who sent the ExecutionRequest?

**Comment by buchgr** [comment]
My understanding of @werkt's request is that he wants to save extra round trips (or is it request overhead?) of requesting the download of output artifacts by inlining them in the result response - correct?

@werkt are you able to quantify the cost?

**Comment by werkt** [comment]
> My understanding of @werkt's request is that he wants to save extra round trips (or is it request overhead?) of requesting the download of output artifacts by inlining them in the result response - correct?

Correct - round trips for comically small requests pay a substantial cost in aggregate request overhead.

> 
> I think inlining of outputs in the response message has it's challenges.
> 
>     * It leads to large message sizes with are bad for performance. Protobuf itself recommends an absolute upper bound of 1MiB.

The size limitations in the request instructions will offer at least some tuning, and prior behavior can be expressed with 0 sizes. "are bad for performance" is somewhat handwavy here - is the performance degradation nonlinear with respect to size? compared to head-of-lined bytestream downloads after?

> 
>     * It introduces complexity in the configuration.

We're doing remote execution of arbitrary commands over a system of interconnected machines. I think the complexity "introduction" avoidance ship has sailed.

> 
>     * It introduces API complexity as some outputs would be fetched inline and others via bytestream (and yet others via batch downloads?).

Bytestream is a required fallback for enormous outputs. Batch downloads are useful for small ones that might have nothing to do with Actions. ActionResult inlining is a logical reduction in expressed operations (cache retrieval or execution) that can be optimized for. I see these all as valid use cases, and I can't see any way to be a better server to a competent client who wants to minimize round trips without this.

> 
> 
> If requesting the fetching of outputs turns out to be expensive, I'd much prefer to convert these calls to streaming calls. This allows us to avoid all the downsides I listed above.

Wouldn't that just be alleviated by not requesting the outputs be inlined at all? Not sure we need another complicated unary -> streaming conversion on the books...

> 
> First though, I think it would be important to quantify the costs. @werkt are you able to quantify the costs somehow?

Working on that now.

**Comment by buchgr** [comment]
> Correct - round trips for comically small requests pay a substantial cost in aggregate request overhead.

Can you quantify "comically small requests"?

> "are bad for performance" is somewhat handwavy here - is the performance degradation nonlinear with respect to size? compared to head-of-lined bytestream downloads after?

If this feature request leads to multi megabyte protobuf messages then this does introduce substantial peak memory increases both on the client and server. I am not sure what you are referring to with "head-of-lined bytestream downloads". 

> Wouldn't that just be alleviated by not requesting the outputs be inlined at all? Not sure we need another complicated unary -> streaming conversion on the books...

A smart man once said :stuck_out_tongue: 

> We're doing remote execution of arbitrary commands over a system of interconnected machines. I think the complexity "introduction" avoidance ship has sailed.

In all seriousness. I think it depends on what the "comically small requests" turns out to be. At least in Bazel we are trying to avoid downloads wherever possible and so I'd prefer for the client to be allowed to be able to choose what he wants to receive. 

Conceptually, a server streaming version of `GetActionResult` seems simple enough and general purpose enough to be used as a replacement for batch downloads, bytestream and inlining for this Bazel codepath.

`GetActionResult(actionKey, 1,5,7) -> stream ActionResult, Output1, Output5, Output7`

**Comment by werkt** [comment]
> Can you quantify "comically small requests"?
> 
Anything under a total of 100k seems laughable for a latency/request penalty requirement. For sizes like that, I would prefer to retain the ActionResults with their outputs in a bundle.

> If this feature request leads to multi megabyte protobuf messages then this does introduce substantial peak memory increases both on the client and server. I am not sure what you are referring to with "head-of-lined bytestream downloads".
> 
Not interested in supporting multi megabytes (or even megabyte). Head of line meaning requiring the ActionResult response to complete before a download could be initiated, necessitating a request latency cost at a minimum.

> > Wouldn't that just be alleviated by not requesting the outputs be inlined at all? Not sure we need another complicated unary -> streaming conversion on the books...
> 
> A smart man once said stuck_out_tongue
> 
I meant requesting a 0 size. Not having the option just locks this into a pattern that can't support inlining.

> Conceptually, a server streaming version of `GetActionResult` seems simple enough and general purpose enough to be used as a replacement for batch downloads, bytestream and inlining for this Bazel codepath.
> 
> `GetActionResult(actionKey, 1,5,7) -> stream ActionResult, Output1, Output5, Output7`

This would be fun. Likewise for Execute

**Comment by ola-rozenfeld** [comment]
After https://github.com/bazelbuild/remote-apis/pull/69 is in, and combined with no-intermediate-downloads, is there anything else remaining to do here?

**Comment by EricBurnett** [comment]
#69 is now in, and agreed that I'm not seeing anything else outstanding in this request, so I too vote to close this issue :).
