### ISSUE TITLE
Execute keepalive client expectations

### ISSUE THREAD

**Issue by werkt** [bazelbuild/remote-apis#48]
We should clarify the expected behavior in the API for streaming responses meant to ensure that an operation is still in progress with long intervals between reported status changes. Namely that operations will be updated with `done = false`, the operation name in place, and either unchanged since the last update or absent metadata.

**Comment by bergsieker** [comment]
Is this a duplicate of https://github.com/bazelbuild/remote-apis/issues/57 or am I missing something?

**Comment by werkt** [comment]
It is, this was probably the result of two successive remote ex API meetings, and forgetting that I had put up a tracker already.
