### ISSUE TITLE
SymlinkAbsolutePathStrategy enum should be wrapped in a message

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/remote-apis#56]
Protobuf's enum scoping follows traditional C/C++ rules, where the enum name is not a new level of namespacing. This means the current definition of `SymlinkAbsolutePathStrategy`:

```proto
message CacheCapabilities {
  enum SymlinkAbsolutePathStrategy {
    UNKNOWN = 0;
    DISALLOWED = 1;
    ALLOWED = 2;
  }
  SymlinkAbsolutePathStrategy symlink_absolute_path_strategy = 5;
```

will define `CacheCapabilities::ALLOWED`, `CacheCapabilities::DISALLOWED`, etc. This is very confusing because the symbols indicate that caching itself is allowed/disallowed, instead of just this one particular feature.

I recommend the following structure instead:

```proto
message SymlinkAbsolutePathStrategy {
  enum Enum {
    UNKNOWN = 0;
    DISALLOWED = 1;
    ALLOWED = 2;
  }
}

message CacheCapabilities {
  SymlinkAbsolutePathStrategy.Enum symlink_absolute_path_strategy = 5;
```

**Comment by ola-rozenfeld** [comment]
I agree that in C++ this is very annoyingly confusing. Moreover, the same problem exists in Python and Go as well, only Java does it right. But I think we should either make this change for all the enums on this proto, or none. The same problem applies to ExecuteOperationMetadata.Stage and DigestFunction, although to a lesser degree because those ones have more self-explanatory names.

Another good thing about your proposal is that it is not a breaking change. I mean, sure, some code would need to change, but it could be done independently in all clients and servers, and the wire format is the same.
So I like it -- I would only switch the name `Enum` for `Value`, just in case (don't want to use reserved words).

@bergsieker WDYT?

**Comment by ulfjack** [comment]
It'll make Java code more annoying, though. Maybe this should be filed against protobuf?

**Comment by jmillikin-stripe** [comment]
@ulfjack I expect there's a zero percent chance of upstream protobuf changing its enum scoping semantics at this point. That ship sailed ten years ago.

**Comment by ola-rozenfeld** [comment]
Agreed. Also, as annoying goes, I much prefer annoyingly slightly more verbose (`SymlinkAbsolutePathStrategy.Value.ALLOWED`) to annoyingly misleading (`CacheCapabilities::ALLOWED`).

**Comment by ulfjack** [comment]
It might still be worth letting them know. They did some rather large changes for proto3, and they might be thinking about this already.

**Comment by ola-rozenfeld** [comment]
Do you prefer that we make this change now, and fix the *compile* of existing clients/servers, or postpone till the next API version?
I'd prefer to just do it.

**Comment by jmillikin-stripe** [comment]
IMO: just do it. This change is backwards-compatible on the wire, and waiting longer only increases the number of clients that would need to update.

**Comment by ola-rozenfeld** [comment]
I haven't, but I did an internal code search and this looks like a common
practice internally. However, very recently internally they had this exact
discussion and added a recommendation to the style guide that suggests
prefixing the enum values with the enum name, e.g:

enum DayOfWeek {
  DAY_OF_WEEK_SUNDAY = 1;
  DAY_OF_WEEK_MONDAY = 2;
  ...
}

I honestly find this pretty bad, and would much rather do the message
wrapping for us, though. But if people strongly prefer the prefix solution,
we can do that instead. Thoughts?

**Comment by jmillikin-stripe** [comment]
The prefix solution is the traditional way, used since proto1 to match C++ style. Wrapping enums in a message only started once protobuf was ported to languages where enum value symbols are namespaced under the type.

My preference is for the wrapper message because LONG_SCREAMING_SNAKE_CASE doesn't match contemporary style in any major language. Even C++ has namespaced enum value symbols nowadays.
