### ISSUE TITLE
Clarify whether nested output directories are permitted

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/remote-apis#63]
The comments for `Command.output_files` state that an output file cannot be the parent of another output file, but there is not a corresponding comment for directories.

Please add a comment to clarify which, if any, of these output layouts are valid:

Output directory is child of another output directory:
```
output_directories: "upper"
output_directories: "upper/lower"
```

Output file is child of output directory:
```
output_directories: "upper"
output_files: "upper/lower"
```

Output directory is child of output file (possible if file is a symlink)
```
output_files: "upper"
output_directories: "upper/lower"
```

**Comment by ola-rozenfeld** [comment]
Anything not explicitly disallowed is allowed:

Output directory/file is child of another output directory: allowed.
Output directory is child of output file: not possible and will not work, because then the output file is not actually file, which will cause a FAILED_PRECONDITION error. If we expect an output to be a symlink to a directory, it should be specified as an output directory, not an output file.

**Comment by ola-rozenfeld** [comment]
... and perhaps it's worth it to clarify this point in the proto :-)
Will do.

**Comment by jmillikin-stripe** [comment]
> Output directory is child of output file: not possible and will not work, because then the output file is not actually file, which will cause a FAILED_PRECONDITION error. If we expect an output to be a symlink to a directory, it should be specified as an output directory, not an output file.

Does this mean that execution servers that preserve symlinks need to test the type of the symlink target? I was previously assuming symlinks were uploaded as-is. If the server is expected to validate the target also, can you add a comment for that?

**Comment by ola-rozenfeld** [comment]
> If the server is expected to validate the target also, can you add a comment for that?

Done. (https://github.com/bazelbuild/remote-apis/pull/74)
Also, in general I would like to remove the explicit type specification of outputs by the client in V3 (https://github.com/bazelbuild/remote-apis/issues/75).
