### ISSUE TITLE
Base64 encoding of RequestMetadata

### ISSUE THREAD

**Issue by finnball** [bazelbuild/remote-apis#70]
Looking at the `RequestMetadata` proto:

> // * contents: the base64 encoded binary `RequestMetadata` message.

https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L1416

It states that the contents should be base64 encoded binary. I don't think this is what Bazel currently does:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/util/TracingMetadataUtils.java#L65

To me it looks as if it is just sending down a raw protobuf. Would it make sense to change the docs to reflect what Bazel currently does as I'm not sure it makes sense to encode it as base64?

**Comment by ola-rozenfeld** [comment]
No, it does actually get encoded as base64. This is done in the gRPC library itself, to all binary headers: https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Metadata.java#L470

**Comment by finnball** [comment]
So the user will never receive it as base64 encoded - this is done by the gRPC library?

**Comment by ola-rozenfeld** [comment]
If the gRPC library is used for dealing with headers on both ends, then yes, the user will not be aware of the base64 encoding. We just thought to mention it in the protocol because we didn't want to be implementation dependent. For example, the RBE server needs to decode the headers from base64, because we don't use the gRPC library there.

**Comment by EricBurnett** [comment]
If most people will be interacting with this proto via gRPC, could we add a
note that it's automatically encoded/decoded via those libraries?
