### ISSUE TITLE
loads in //build/bazel/remote/execution/v2 induce dependencies

### ISSUE THREAD

**Issue by werkt** [bazelbuild/remote-apis#78]
The loads of grpc and rules_go starlark methods mandate that any workspace that references the //build/bazel/remote/execution/v2 package - even to non-language targets - provide both the rules_go and grpc repositories. This will break implementors that do not have these dependencies already, and require that wholly unrelated implementations (i.e. buildfarm in Java) include declarations for these go and grpc repos, that must match by name.

If remote-apis is going to continue down this path of providing language implementations (C++ and go so far), it should provide an extension library for initializing the repo with these dependencies activated, and personally I would like to have these available in separate packages by language, if only to make it possible not to import the growing list of supported language rules toolchains.

**Comment by ola-rozenfeld** [comment]
Something odd is going on here -- for example, I have a my own fork of tools_remote https://github.com/ola-rozenfeld/tools_remote/blob/tool/WORKSPACE which depends on remote-apis but doesn't have rules_go as a dependency, yet it compiles just fine.
What Bazel version are you using?

**Comment by ola-rozenfeld** [comment]
Disregard, I reproduced it. Java builds are failing without rules_go. Will look into this.

**Comment by jasharpe** [comment]
I introduced the go_rules dependency. I'll look into this and try to fix it so that manual users don't need to include it.

**Comment by jasharpe** [comment]
My plan is to use the same solution as https://github.com/googleapis/googleapis, which provides an workspace initialization function that allows you to specify which languages you want: https://github.com/googleapis/googleapis/blob/master/WORKSPACE#L11

It supplies default no-op implementations of rules for languages you aren't using.
