### ISSUE TITLE
go get fail

### ISSUE THREAD

**Issue by ukai** [bazelbuild/remote-apis#82]
go get fails with the recent commit

..
go: extracting github.com/bazelbuild/remote-apis v0.0.0-20190524141337-c0682f068a60
-> unzip /usr/local/google/home/ukai/go/pkg/mod/cache/download/github.com/bazelbuild/remote-apis/@v/v0.0.0-20190524141337-c0682f068a60.zip: case-insensitive file name collision: "BUILD" and "build"

**Comment by bergsieker** [comment]
@jasharpe Can you take a look at this?

**Comment by ukai** [comment]
might be a bug in go toolchain, but I feel it might be potential problem if used on windows.

**Comment by jasharpe** [comment]
I'll look into this.
